service: poc-be

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  stage: dev

custom:
  stage: ${opt:stage, self:provider.stage}

resources:
  Resources:
    CognitoAuthenticatedUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${self:custom.stage}-authenticated-user-pool
        UsernameAttributes:
          - email
        AutoVerifiedAttributes:
          - email
    CognitoAuthenticatedUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: ${self:custom.stage}-authenticated-user-pool-client
        UserPoolId:
          Ref: CognitoAuthenticatedUserPool
        ExplicitAuthFlows:
          - ALLOW_ADMIN_USER_PASSWORD_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
        GenerateSecret: false
