service: api


provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  lambdaHashingVersion: 20201221
  environment:
    PRODUCTS_TABLE: ${self:custom.productsTable}
  apiGateway:
    shouldStartNameWithService: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource: '*'

package:
  individually: true

plugins:
  - serverless-webpack

custom:
  productsTable: products-table
  cognitoPoolId: eu-west-1_pLyAjCA0M
  cognitoPoolCliId: 7cv4vjr9p3o5ttbgneucg1463c
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

functions:
  getProduct:
    handler: src/endpoints/getProduct.handler
    description: Get product by ID
    events:
      - http:
          path: product/{ID}
          method: GET
          cors: true
  getProducts:
    handler: src/endpoints/getProducts.handler
    description: Get all products
    events:
      - http:
          path: products
          method: GET
          cors: true
  postProduct:
    handler: src/endpoints/postProduct.handler
    description: Add a new product by ID
    events:
      - http:
          path: product/{ID}
          method: POST
          cors: true
          authorizer: 
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer
 
resources:
  Resources: 
    ProductsTable: 
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.productsTable}
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    ApiGatewayAuthorizer:
      Type: AWS::ApiGateway::Authorizer
      Properties:
        AuthorizerResultTtlInSeconds: 300
        IdentitySource: method.request.header.Authorization
        Name: Cognito
        RestApiId: 7skg4i18y5 
        Type: COGNITO_USER_POOLS
        ProviderARNs:
          - arn:aws:cognito-idp:eu-west-1:501082649462:userpool/eu-west-1_pLyAjCA0M 
