service: api

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  profile: sls-admin
  lambdaHashingVersion: 20201221
  environment:
    ENV: ${self:provider.stage}
    REGION: ${self:provider.region}
    SLS_DEBUG: '*'
    PRODUCTS_TABLE: ${self:custom.productsTable}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: '*'

package:
  individually: true
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#   - node_modules

plugins:
  - serverless-plugin-typescript

custom:
  productsTable: products-table

functions:
  getProduct:
    handler: src/endpoints/getProduct.handler
    description: Get product by ID
    events:
      - http:
          path: product/{ID}
          method: GET
          cors: true
  postProduct:
    handler: src/endpoints/postProduct.handler
    description: Add a new product by ID
    events:
      - http:
          path: product/{ID}
          method: POST
          cors: true

resources:
  Resources: 
    ProductsTable: 
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.productsTable}
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5